apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dharmtest-poi-backend-app-dev
  annotations:
    argocd/app-name: dharmtest-poi-backend-app-dev
    backstage.io/kubernetes-id: dharmtest-poi-backend-app
    backstage.io/kubernetes-namespace: dharmtest
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/dharmtest-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/dharmtest/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/dharmtest/deployments/dharmtest-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/dharmtest-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/pdharmavaram"
  system: workshop-system-dharmtest
  providesApis:
    - backend-api-dharmtest
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-dharmtest
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/pdharmavaram"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-dharmtest
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://dharmtest-poi-backend-app-dharmtest.apps.j0i9yf30.eastus2.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-atl/dharmtest-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/pdharmavaram"
  system: workshop-system-dharmtest
  definition:
    $text: https://github.com/rhdh-atl/dharmtest-backend/tree/main/src/main/resources/META-INF/openapi.yaml
